version: '3.7'
services: 
  vue:
    container_name: vue_${APP_NAME}
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT}:8080
    working_dir: /usr/src/app/${APP_NAME}
    volumes:
      - ./${APP_NAME}:/usr/src/app/${APP_NAME}
      - ./commands:/usr/src/app/commands
    tty: true
